### ISSUE TITLE
glibc detected *** oases: double free or corruption (!prev)

### ISSUE THREAD

**Issue by msbanos** [dzerbino/oases#8]
Seeing the following stack dump for a specific kmer size of 27 (I've tried 17 - 25, and 29 - 31 and they work fine):

```
======= Backtrace: =========
/lib64/libc.so.6[0x3e1d475e76]
/lib64/libc.so.6[0x3e1d4789b3]
oases[0x4264de]
oases[0x42679a]
oases[0x40d4b6]
oases[0x4022cd]
/lib64/libc.so.6(__libc_start_main+0xfd)[0x3e1d41ed5d]
oases[0x401839]
======= Memory map: ========
00400000-0043b000 r-xp 00000000 fd:00 646203                             /opt/oases_0.2.8/oases
0063b000-0063c000 rw-p 0003b000 fd:00 646203                             /opt/oases_0.2.8/oases
0202d000-047bb000 rw-p 00000000 00:00 0                                  [heap]
3e1d000000-3e1d020000 r-xp 00000000 fd:00 545874                         /lib64/ld-2.12.so
3e1d21f000-3e1d220000 r--p 0001f000 fd:00 545874                         /lib64/ld-2.12.so
3e1d220000-3e1d221000 rw-p 00020000 fd:00 545874                         /lib64/ld-2.12.so
3e1d221000-3e1d222000 rw-p 00000000 00:00 0 
3e1d400000-3e1d58a000 r-xp 00000000 fd:00 546098                         /lib64/libc-2.12.so
3e1d58a000-3e1d78a000 ---p 0018a000 fd:00 546098                         /lib64/libc-2.12.so
3e1d78a000-3e1d78e000 r--p 0018a000 fd:00 546098                         /lib64/libc-2.12.so
3e1d78e000-3e1d78f000 rw-p 0018e000 fd:00 546098                         /lib64/libc-2.12.so
3e1d78f000-3e1d794000 rw-p 00000000 00:00 0 
3e1d800000-3e1d883000 r-xp 00000000 fd:00 545853                         /lib64/libm-2.12.so
3e1d883000-3e1da82000 ---p 00083000 fd:00 545853                         /lib64/libm-2.12.so
3e1da82000-3e1da83000 r--p 00082000 fd:00 545853                         /lib64/libm-2.12.so
3e1da83000-3e1da84000 rw-p 00083000 fd:00 545853                         /lib64/libm-2.12.so
3e1e400000-3e1e415000 r-xp 00000000 fd:00 545931                         /lib64/libz.so.1.2.3
3e1e415000-3e1e614000 ---p 00015000 fd:00 545931                         /lib64/libz.so.1.2.3
3e1e614000-3e1e615000 r--p 00014000 fd:00 545931                         /lib64/libz.so.1.2.3
3e1e615000-3e1e616000 rw-p 00015000 fd:00 545931                         /lib64/libz.so.1.2.3
3e20000000-3e20016000 r-xp 00000000 fd:00 546082                         /lib64/libgcc_s-4.4.7-20120601.so.1
3e20016000-3e20215000 ---p 00016000 fd:00 546082                         /lib64/libgcc_s-4.4.7-20120601.so.1
3e20215000-3e20216000 rw-p 00015000 fd:00 546082                         /lib64/libgcc_s-4.4.7-20120601.so.1
7f11c4da5000-7f11c522d000 rw-p 00000000 00:00 0 
7f11c531b000-7f11c53c9000 rw-p 00000000 00:00 0 
7f11c55d3000-7f11c56f8000 rw-p 00000000 00:00 0 
7f11c5922000-7f11c59a0000 rw-p 00000000 00:00 0 
7f11c5c63000-7f11c5cde000 rw-p 00000000 00:00 0 
7f11c62f1000-7f11c65a8000 rw-p 00000000 00:00 0 
7f11c6629000-7f11c68c1000 rw-p 00000000 00:00 0 
7f11c788e000-7f11c80b3000 rw-p 00000000 00:00 0 
7f11c93de000-7f11c93e2000 rw-p 00000000 00:00 0 
7f11c93ee000-7f11c93f0000 rw-p 00000000 00:00 0 
7fff22151000-7fff22167000 rw-p 00000000 00:00 0                          [stack]
7fff221ff000-7fff22200000 r-xp 00000000 00:00 0                          [vdso]
ffffffffff600000-ffffffffff601000 r-xp 00000000 00:00 0                  [vsyscall]
Traceback (most recent call last):
  File "/usr/bin/oases_pipeline.py", line 121, in <module>
    main()
  File "/usr/bin/oases_pipeline.py", line 115, in main
    singleKAssemblies(options)
  File "/usr/bin/oases_pipeline.py", line 46, in singleKAssemblies
    assert p.returncode == 0, "Oases failed at k = %i\n%s" % (k, output[0])
AssertionError: Oases failed at k = 27
```

**Comment by drosofff** [comment]
I have a weird similar error using oases in a galaxy wrapper we developped (see https://toolshed.g2.bx.psu.edu/repository/browse_repository?id=eb9b0cf2879f5df1)

```
*** Error in `oases': double free or corruption (!prev): 0x0000000000e3bd20 ***
/bin/sh: line 1:  2774 Aborted                 (core dumped) oases /var/storage/job_working_directory/034/34883/outputFolder_19
```

This error occurs in the khmer range **19**-69, 19 being the faulty parameter. 21(and higher)-69 works fine.

The really strange thing is that, this error seems to be "sequence" specific.

I can reproduce it consistently with 4 sequences datasets, and only these datasets, among >200 sequence datasets I have been using since I work with oases.

I put one of these 4 datasets in gist : https://gist.github.com/drosofff/e1e9c7d5efbb1da54e35#file-faulty_oases_input-fa

**Comment by dzerbino** [comment]
@msbanos: My apologies for the slow response. I would need more info on the crash, it could be anything really. Was anything printed below the last line?

**Comment by dzerbino** [comment]
@drosofff Could you please create a separate issue? It'll make communication simpler. Thanks!

**Comment by msbanos** [comment]
@dzerbino what will be the easiest way to pass along data privately?

**Comment by dzerbino** [comment]
How big is the file?

**Comment by drosofff** [comment]
@dzerbino Sorry also for the slow response to your response. I create another separate issue

**Comment by msbanos** [comment]
@drosofff sorry for the delayed response.  The files we were using as inputs were temp files which have since gotten deleted.  I've been unable to reproduce with the same data set, but our upstream processing has changed so we have different sequences being fed into the assembler.  I'm going to close this until I can reproduce and grab files.
